description: has a lot to do
gist:
  noscript: false
highlighter: rouge
incremental: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
lsi: false
safe: true
theme: jekyll-theme-primer
title: a rain dog too
